### ISSUE TITLE
Yhteiset työskentelytavat

### ISSUE THREAD

**Issue by nikcorg** [iojs/iojs-fi#12]
Voitaisiin kirjata ylös pelisäännöt yhteen paikkaan, nyt niitä on ripoteltuina eri tiketeissä. Kirjasin tähän ne mitä löysin, ja sävelsin pari omasta päästä (toimitusmuoto ja formaatti).
- Käännökset toimitetaan Pull Requesteilla
- Käännöksen muoto on GitHub-flavoured Markdown muotoiltua tekstiä
- Käännös sisältää aina linkin alkuperäiseen juttuun
- Tiedostot nimetään alkuperäisen jutun julkaisupäivämäärän mukaan, esim. `2015-02-10-otsikko.md`
- Tiedostot tallennetaan kunkin kontekstin omaan kansioon, esim. `blog/` blogiteksteille, `website/content/fi` iojs.org-sivuston lokalisoinneille.
- Yhteinen termistö kootaan sanastoksi `GLOSSARY.md`-tiedostoon (@ruksi oliko tämä jo tulossa sulta? Taisit [aloittaa sen ainakin](https://github.com/iojs/iojs-fi/issues/6#issuecomment-74250428))
- Puuttuva termistö lainataan mahdollisuuksien mukaan muualta (kerätään linkkilistaa sanastoihin sitä mukaan kun löytyy), käännetään lonkalta, mankeloidaan finglishiksi, tai käytetään sellaisenaan (esim. GitHubin termit ja käyttöliittymään liittyvä sanasto)

Täydennetään tätä tikettiä ja kootaan lopuksi siitä toimintaohje.

@paazmaya

**Comment by ruksi** [comment]
Joo se sanasto on olemassa jo, voin pistää siitä pull requestin vielä tänään.

Nuo työskentelytavat voin tehdä kans, kääsinkin jo sen iojs/websiten työskentelydokkarin mutta ei se kyllä meille suoraan sovi, eli teen uuden. Sitä voi sitten muokata tarpeen mukaan.

Tuosta kansiorakenteesta: mun alkuperäinen idea oli että eri "repot" tai "kontekstit" olis jo jo juuresta lähetien eri kansioissa ja että kansiorakenne seuraisi alkuperäisen repon rakennetta mahdollisimman tarkkaan, sori etten selventänyt sitä alkuperäisessä ehdotuksessa.

``` bash
# <REPO_TAI_KONTEKSTI>/<REPON_RAKENNE>
blog/ # kaikki artikkelit esim. 2015-02-10-otsikko.md, eri kansiossa kun website koska ne julkaistaan mediumissa
website/content/fi # ne 4 filua jotka on sielllä iojs/website repossa samanlaisessa rakenteessa
iojs # kaikki käännökset jotka suoraan liittyvät iojs repon sisältöön, kuten API dokumentaatio
iojs/doc # API dokumentaatio, koska se on io.js:n repossa
```

**Comment by paazmaya** [comment]
Olettepa te nopeita.

@ruksi ehdottama kansiorakenne näyttää hyvältä, mennään sillä.

@nikcorg voit laittaa tuon listan suoraan `README.md`, samoin kuin tuo @ruksi kansiorakenne selitys

**Comment by nikcorg** [comment]
@ruksi Oliko sulla tää vielä työn alla?

**Comment by ruksi** [comment]
Lisäsin READMEhin tärkeimmät asiat mitä tässä issuessa on keskusteltu [-> PR](https://github.com/iojs/iojs-fi/pull/23).
