### ISSUE TITLE
käännä uusin blogiposti 2015-02-06

### ISSUE THREAD

**Issue by httpsterio** [iojs/iojs-fi#4]

**Comment by nikcorg** [comment]
Oliko tämä sulla @alajarvela jo työn alla?

**Comment by paazmaya** [comment]
Kun on ensimmäinen posti valmiina, julkaistaan se täällä https://medium.com/@iojs_fi, johon pääsee Twitter tunnuksilla, jotka jaan spostitse heti kun on tarvetta ja julkaistavaa.

**Comment by httpsterio** [comment]
@nikcorg joo se on itseasiassa tehty, pitää vaa kattoo just miten tehdään finglishin kanssa teknisen sanaston osalta ja jotain kieliopin korjausta. Mites noita tekstejä laitetaan, omaan branchiin, omaan kansioon vai jaetaanko täällä drafteja Mediumista ja julkastaan suoraan vaa oikealla tilillä sit? Markdownia vai mitenkäs, Mediumissa kuitenkin muotoillaan lopullisesti.

**Comment by nikcorg** [comment]
Eikö Pull Request olisi looginen mekanismi?

**Comment by paazmaya** [comment]
@alajarvela oletko vielä tekemässä tätä käännöstä? Voisitko jakaa sitä Pull Requestin muodossa?

**Comment by nikcorg** [comment]
Onko tämä vielä hengissä?
