### ISSUE TITLE
API dokumentaatio

### ISSUE THREAD

**Issue by paazmaya** [iojs/iojs-fi#5]
https://iojs.org/api/index.html

Tämän voisi pyrkiä kääntämään sivu/metodi kerrallaan, seuraten samaa järjestystä ja rakennetta kuin alkuperäisessä.

**Comment by nikcorg** [comment]
@paazmaya Tuohan on lähdekoodista generoitua dokumentaatiota. (Tsek: https://github.com/iojs/doc-tool) Käännöksen ajan tasalla pitäminen kuulostaa Sisyfoksen helvetiltä. Kuuluuko se oikeasti tämän projektin piiriin, vai onko tarkoitus kääntää korkeamman tason dokumentaatiota?

**Comment by ruksi** [comment]
@nikcorg jotkut kieliryhmät kääntävät tuota API dokumentaatiotakin, tuo APIn dokumentaatio löyty ainaki [iojs/io.js/../api](https://github.com/iojs/io.js/tree/v1.x/doc/api) mutta mielestäni siihen liittyen ei ole iojs tasolta tullut mitään ohjeistusta miten se sitten liitetään pääprojektiin, eli ainut tapa tällä hetkellä olisi hostata tämä suomenkielinen dokumentaatio itse. Tuo dokumentaatiota ei ainakaan suoraan käännetä lähdekoodista kun vertaa esim: [buffer.cc](https://github.com/iojs/io.js/blob/v1.x/src/node_buffer.cc), [buffer.h](https://github.com/iojs/io.js/blob/v1.x/src/node_buffer.h) ja [buffer.js](https://github.com/iojs/io.js/blob/v1.x/lib/buffer.js) vs [buffer dokumentaatio](https://github.com/iojs/io.js/blob/v1.x/doc/api/buffer.markdown), tai en vaan löydä niiden alkuperää.

Ilmeisesti näiden käännösprojektien alkuperäinen tarkoitus oli kääntää tuo iojs kotisivu suomeksi, eli 4 sivua, viitaten [iojs/website/TRANSLATION.md](https://github.com/iojs/website/blob/master/TRANSLATION.md)

Jotkut myös puhuivat blogipostien kääntämisestä iojs:n puolelta.

Eli itse tekisin tähän repoon vaan website/content/fi kansion ja sinne 4 käännettyä filua, ja tehdään niistä aina "release" pull requestilla tuohon iojs/website repoon. Näin voi myöhemmin ruveta tekemään API käännöstä kansioon doc/ ja blogipostikäännöksiä kansioon blog/. Samallaittee tekevät ainakin velivenäläiset [iojs/iojs-ru](https://github.com/iojs/iojs-ru)

**Comment by paazmaya** [comment]
Suljetaan tämä toistaiseksi ja keskitytään ensin noihin edellä esitettyihin käännöksiin.
