### ISSUE TITLE
Ryhmään liittyminen

### ISSUE THREAD

**Issue by paazmaya** [iojs/iojs-fi#6]
Ketkä ovatkaan kiinnostuneita tekemään käännöksiä suomenkielelle, kommentoikaa tähän ... issuehen.

Kenties @alajarvela, @nikcorg, @gorillasaurus, @ruksi ?

Yhteisen toiminnan kuvioita luodaan sitä mukaa kun ryhmä rakentuu...

**Comment by ruksi** [comment]
Kiinnostusta löytyy, ohjeita tai tehtäviä esille ni käännän kun kerkiän :)

**Comment by paazmaya** [comment]
Haluaisitko @ruksi kääntää tämän https://github.com/iojs/website/blob/master/GOVERNANCE.md jolloin tulisi ohjeetkin tutuksi?

**Comment by ruksi** [comment]
Ok, käännän

**Comment by ruksi** [comment]
Meidän pitäisi myös tehdä linjaukset yksittäisten vakiintuneiden termien kääntämisestä. 

Esimerkiksi "GitHub repository hosting" voi kääntää sanasta sanaan "GitHub säilytyspaikan isännöinti" mutta kuulostaa huonommalta kuin ”GitHub repositoryn hostaus”. Sama ongelma termille "Collaborator", onko se "Osallistuja", "Avustaja", "Työtoveri" vai pelkästään "Collaboraattori". 

Itse suosittelen tätä finglish että "hosting" on "hostaus" ja "Colloborator" on "Collaboraattori" jolloin ei tarvitse arvata mitä esimerkiksi "Avustaja" tässä asiakyhteydessä tarkoittaa.

**Comment by ruksi** [comment]
Sitten tarkentava huomio olen nyt kääntänyt tuota [GOVERNANCE.md](https://github.com/iojs/website/blob/master/GOVERNANCE.md) sillä mielin että se olisi tämän käännösprojektin käytöntöohjeistuksen pohja, en sillä lailla että se olisi iojs:n verkkosivun ohjeistuksen käännös. Oma ohjeistus pitää olla kunnossa ennenkuin voi ruveta oikeasti kääntämään.

Tästä seuraa esim. kysymys että onko meillä täysin samat käytännöt kuin tuossa dokumentissa, mm:
- Pitääkö Työrymä viikottaisia tapaamisia Hangoutissa jotka pistetään YouTubeen kaikkien katsottavaksi.

Työryhmää suositellaan olevaksi iojs/website [TRANSLATION.md](https://github.com/iojs/website/blob/master/TRANSLATION.md) ohjeistuksessa, mutta itse en nää tarpeelliseksi pitää viikottaisia tapaamisia tai että me upattais niitä YouTubeen. Ehdotan itse että pidetään tapaamiset yhden viikon varotusajalla niin että asialista on lyöty lukkoon.

Mutta itselle ehkä tärkein kysymys on miten käännöksen pull requestaaminen sitten käytännössä menee. Ilmeisesti joku tekee forkin iojs/website, kopio meidän reposta sisällön tuonne iojs/websiten content/fi kansioon (4 filua) ja pull requestia menemään jokaisen uuden version kohdalla. En ainakaan itse heti keksinyt parempaa tapaa. Ehdotan myös että Työryhmä hoitaa uusien versioiden päivittämisen tuonne iojs/websiten päärepoon.

**Comment by paazmaya** [comment]
Kiitos @ruksi !

Ei liene tarvetta viikottaisille tapaamisille, niitä pidettäneen kun tarve ilmenee.

Kaikista (isommista) muutoksista voisi tästä eteenpäin tehdä pull requestin ilman forkkia, koska kaikilla ryhmään kuuluvilla tulee olemaan suora commit oikeus. Kyseisen pull requestin mergaa sitten joku muu ryhmän jäsen. Mahdollisesti ryhmän kasvaessa voi vaatia että myös kolmas henkilö käy PR:n läpi.

Uudet jäsenet voivat tehdä forkin josta PR, ennen kuin ovat ryhmä ja siten tämän repon kontribuuttoreita.

Niin ja nyt kun luin viestin uudelleen, niin joo, iojs/website fork PR seems to be the way to go.

**Comment by nikcorg** [comment]
@ruksi tuo yhteinen sanasto on kyllä hyvä pointti. Suosittelisin kuitenkin - ennen kuin keksimme oman pyörämme, että tsekataan esim. GNU-/Gnome-projektien sanastoa. Niistä ei välttämättä löydä kaikkia tarvittavia sanoja, mutta IT-/ATK-termistö on varmasti ihan kattava. Luodun sanaston voisi myös koota omaksi dokumentikseen.

Subjektiivisena mielipiteenä, kollaboraattori on kyllä melkoinen sanahirviö. Hostauksen sulatan helposti.

**Comment by ruksi** [comment]
@nikcorg joo katsoin äsken vähän muoden lokalisointujen projektien sanastoa läpi, kyllä sieltä jotain sanoja löytyi.

Teen tästä erillisen pull requestin mutta tässä nyt tähän keskusteluun liittyen pieni koottu sanasto, heittäkää vaan muutosehdotuksia jos tulee mieleen.

Noita GitHubiin tiukasti liittyviä sanoja on huono suomentaa ihan sen takia että tämä käyttöliittymä on kuitenkin englanniksi.

GLOSSARY.md

| EN | FI |
| --- | --- |
| governance | hallinto |
| work group | työryhmä |
| collaborator | toimija |
| contribution | työpanos, osallistuminen |
| policy | linjaus |
| guideline | ohjeistus |
| agenda | asialista |
| repository | repository |
| issue | issue |
| commit | commit |
| pull request | pull request |
| hosting | hostaus |
| consensus-seeking decision-making | yhteisymmärrykseen tähtäävä päätöksenteko |

**Comment by httpsterio** [comment]
Jep, kiinnostunut. Just tuon yhteisen sanaston kanssa vähän kamppailen, toisaalta semmone Finglish ei ole aina kovin esteettistä, joskin väkisin käännetyt termit taas on hyvin vaikeaselkosia. Pitäis Varmaan kirjottaa joku oma sanakirja Wikiin tms?

**Comment by nikcorg** [comment]
@paazmaya niin, ja alkuperäiseen kysymykseen, olen kiinnostunut osallistumaan. Vapaa-aikani ei (valitettavasti) ole ylitsepursuavan runsasta, mutta sen suomissa rajoissa autan mielelläni.

**Comment by paazmaya** [comment]
@alajarvela ja @nikcorg lisäsin teidät uuri ryhmä jäseniksi. @ruksi olikin siellä jo.

Tervetuloa mukaan ja kuten mainittiin niin varmaankin kaikille yhteistä ettei käytettävissä olevaa aikaa ole liikaa.
