### ISSUE TITLE
Ensimmäinen ryhmän jäsenten tapaaminen

### ISSUE THREAD

**Issue by paazmaya** [iojs/iojs-fi#9]
Olisi kiva tavata kasvotusten, ainakin siltä osin kuin se vain on mahdollista, ottaen huomioon mahdolliset pitkätkin etäisyydet kuten Helsinki - Jyväskylä.

Olisiko ehdotuksia paikan, ajan ja viestimen suhteen?

Vaikkapa Skype, lounasaikaan viikolla tai viikonloppuna? Viikolla 9, 10?

**Comment by ruksi** [comment]
Mulle käy lounasaikaan viikoilla 9 ja 10 kaikki muut päivät paitsi eivät PE 27.2.ja KE 4.3.

**Comment by nikcorg** [comment]
Google Hangout on "kasvotusten" tapaamiseen kai parempi. Skypessä ryhmävideopuhelut on muistaakseni Premium-fiitsa.

Lounasaikaan mulle käy torstai- ja perjantaipäivät. Iltaisin paremmin.

Irkkaatteko muut? Minut löytää IRCnetistä nimellä nikc. Perustetaanko #iojs-fi/IRCnet?

Muutoin majailen Helsingissä ja käyn mielelläni bissellä.

**Comment by paazmaya** [comment]
Minäkin seikkailen Helsingissä, onko vielä muita täällä?

**Comment by paazmaya** [comment]
Hups, on jo jälkimmäinen viikko ehdotetuista, mutta kovat kiireet töissä ovat estäneet muun toiminnan...
